# Generated by Django 5.2.6 on 2025-09-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="bodegas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventarios",
                to="core.bodega",
            ),
        ),
    ]
