# Generated by Django 5.2.6 on 2025-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_inventario_bodegas"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodega",
            name="latitud",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bodega",
            name="longitud",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
